inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
    - 'ext/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Steepfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/IndexedLet:
  Enabled:
    false
