inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
    - 'ext/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Steepfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/FormatParameterMismatch:
  Exclude:
    - lib/rumale/dataset.rb
